package worklab23;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

public class loginPage extends javax.swing.JPanel {

    /*
    Giris sayfasini iceren sayfa.
     */
    public loginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        emailText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("E Posta:");

        jLabel2.setText("Şifre:");

        enterButton.setText("Giris");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        newButton.setText("Kayıt Ol");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");
        jLabel3.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(passwordText))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enterButton))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButton)
                    .addComponent(newButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        dbConnect msql = new dbConnect();
        Connection con = msql.getConnection(); //Veritabanına baglan.

        String username = emailText.getText(); //Sifre ve e postayi kaydettim.
        String password = passwordText.getText();
        int id = -1;
        try {
            Statement stmt = con.createStatement();
            String sorgu = String.format("Select * from user where mail = '%s' and password='%s'", username, password);
            ResultSet rs = stmt.executeQuery(sorgu);
            //girilen sifre ve e postaya sahip herkesi sorguladim.

            int count = 0; //Ayni e postayla kac kisi var tutan degisken.
            while (rs.next()) {
                count++;
                id = rs.getInt(1);
            }
            if (count == 1) { //Eger 1 kisi varsa buraya girer.
                System.out.println("Giris Basarili");

                JFrame mp = new JFrame(); //Yeni bir pencere acar.
                mp.setSize(500, 500); //boyut
                mp.setLocation(400, 200); //Pozisyon
                searchPanel p2 = new searchPanel(); //Yeni bir arama paneli olusturdum.
                watchPanel p1 = new watchPanel(id, p2.tempLibrary); //Yeni bir izleme paneli olusturdum
                //Filmnlerin gecici olarak tutuldugu arraylist de izleme paneline gonderilir.
                JTabbedPane tp = new JTabbedPane(); //Sekme yapisi olusturdum.
                tp.setBounds(10, 10, 400, 400); //Sekmenin boyutlari.
                tp.addTab("Izle", p1); //Arama ve izleme panelini sekme olarak ekledim.
                tp.addTab("Bul", p2);
                mp.add(tp);//Jtabbedpane(sekme) yapisini yeni pencereye ekledim.
                mp.setVisible(true); //Yeni pencereyi gorunur yaptim.
                mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                JFrame f1 = (JFrame) SwingUtilities.getWindowAncestor(this); //Giris sayfasini kapattim.
                f1.setVisible(false);
                jLabel3.setText("Giris Basarili.");
                jLabel3.setVisible(true);
            } else if (count == 0) {
                //girilen bilgilerde kimse yoksa buraya girer.
                System.out.println("E posta veya sifre hatali");
                jLabel3.setText("E posta veya sifre hatali");
                jLabel3.setVisible(true);
            } else {
                //Girilen bilgilerde birden cok kisi varsa buraya girer.
                System.out.println("Coklu kullanici hatasi.");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }

        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(searchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_enterButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        //Kayit penceresini acan buton.
        registerPage rp = new registerPage(); //yeni bir kayit panel tanimlar.
        JFrame jf = new JFrame(); //Yeni bir pencere tanimlar.
        jf.getContentPane().add(rp); //Kayit panelini pencereye yukler.
        jf.setVisible(true);
        jf.setLocation(400, 200);
        jf.setSize(600, 500); //Boyut ve yer ayarlamalari.


    }//GEN-LAST:event_newButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailText;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField passwordText;
    // End of variables declaration//GEN-END:variables
}
