package worklab23;

import java.sql.Connection;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import org.jdesktop.swingx.prompt.PromptSupport;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class registerPage extends javax.swing.JPanel {
    //Kayit olma sayfasini iceren Jpanel classi.

    private ArrayList<JCheckBox> list; //Film turlerini tutmak icin Checkbox dizisi.

    public registerPage() {
        initComponents();
        list = new ArrayList<>();
        list.add(box1); //10 adet turun listeye eklenmesi.
        list.add(box2);
        list.add(box3);
        list.add(box4);
        list.add(box5);
        list.add(box6);
        list.add(box7);
        list.add(box8);
        list.add(box9);
        list.add(box10);
    }

    private int choosedNumber() { //Kac adet tur secildigini donduren fonksiyon.
        int x = 0;
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).isSelected() == true) {
                x++; //Film seciliyse sayiyi bir arttir.
            }
        }
        return x; //Secilen film sayisini dondurur.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateText = new javax.swing.JFormattedTextField();
        registerButton = new javax.swing.JButton();
        box4 = new javax.swing.JCheckBox();
        box2 = new javax.swing.JCheckBox();
        box1 = new javax.swing.JCheckBox();
        box5 = new javax.swing.JCheckBox();
        box10 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();
        box9 = new javax.swing.JCheckBox();
        box6 = new javax.swing.JCheckBox();
        box8 = new javax.swing.JCheckBox();
        box7 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        lastText = new javax.swing.JLabel();

        jLabel1.setForeground(new java.awt.Color(255, 102, 255));
        jLabel1.setText("Kayıt Ol");

        jLabel2.setText("E Mail:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Ad:");

        jLabel4.setText("Şifre:");

        jLabel5.setText("Doğum Tarihi:");

        dateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });
        PromptSupport.setPrompt("Gun/Ay/Yil", dateText);

        registerButton.setText("Kayıt Ol");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        box4.setText("Çocuk ve Aile");

        box2.setText("Bilim Kurgu ve Fantastik Yapımlar");

        box1.setText("Aksiyon");

        box5.setText("Belgesel");

        box10.setText("Bilim ve Doğa");

        box3.setText("Dramalar");

        box9.setText("Gerilim");

        box6.setText("Komedi");

        box8.setText("Korku");

        box7.setText("Romantizm");

        jLabel6.setText("3 Farklı Tür Seçiniz:");

        lastText.setText("jLabel7");
        lastText.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mailText)
                        .addComponent(nameText)
                        .addComponent(passwordText)
                        .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addComponent(box9)
                    .addComponent(box8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(box10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(box5)
                                .addComponent(box2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box6)
                                    .addComponent(box3)
                                    .addComponent(box7)))))
                    .addComponent(box1))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1)
                    .addComponent(box5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box2)
                    .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box4)
                    .addComponent(box3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box9)
                    .addComponent(box6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box8)
                    .addComponent(box7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lastText)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String name = nameText.getText(); //Ad bilgisini degiskene esitleme islemi.
        String mail = mailText.getText(); //Mail bilgisini degiskene esitleme islemi.
        String password = passwordText.getText(); //Sifre bilgisini degiskene esitleme islemi.
        java.util.Date javadate = (java.util.Date) dateText.getValue();
        java.sql.Date sqldate = new Date(javadate.getTime()); //Dogum bilgisini degiskene esitleme islemi.
        int[] oneriId = new int[3]; //Oneri sunulacak 3 adet turun idsini tutan dizi.
        if (choosedNumber() != 3) { //3 film secilmediyse buraya girer.
            lastText.setText("3 Adet tür seçiniz.");
        } else if (name.length() < 2 || mail.length() < 2 || password.length() < 2) {
            lastText.setText("Bilgilerinizi doğru şekilde giriniz.");
            //isim, mail ya da sifre bilgisi 2 karakterden azsa buraya girer.
        } else { //Eger 3 secim yapildiysa
            int j = 0;
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).isSelected()) {
                    oneriId[j++] = i + 1;  //Secili olan filmlerin idlerini diziye kaydeder.
                }
                if (j == 3) {
                    break; //3 adet tur eklendigi zaman dongu sonlanir.
                }
            }

            dbConnect msql = new dbConnect(); //Veritabani baglantisi.
            Connection con = msql.getConnection();

            try {
                Statement stmt = con.createStatement();
                String sorgu = String.format("insert into user (name, mail, password, borndate) "
                        + "values('%s', '%s', '%s', '%s')",
                        name, mail, password, sqldate);
                //Kisi bilgilerinin veritabanina kaydolmasini saglayan sql sorgusu.
                stmt.executeUpdate(sorgu); //sorgunun islenmesi.

                lastText.setText("Kayıt başarıyla tamamlandı.");
            } catch (SQLException e) {
                System.out.println(e); //Eger ayni bilgilerde baska kullanici varsa.
                lastText.setText("Aynı bilgilere sahip başka bir kullanıcı tespit edildi.");
            }
            JFrame frame = new JFrame(); //Onerileri gostermek adina yeni bir pencere acilmasi.
            frame.setSize(400, 400); //Pencerenin boyutu.
            frame.getContentPane().add(new recomendPanel(oneriId)); //Yeni pencereye oneri panelinin eklenmesi.
            frame.setLocation(400, 300); //Yeni pencerenin yerinin belirlenmesi.
            frame.setVisible(true); //Yeni pencerenin gorunur yapilmasi.

            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(searchPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        lastText.setVisible(true); //Uyari mesajinin gosterilmesi.

    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box10;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box3;
    private javax.swing.JCheckBox box4;
    private javax.swing.JCheckBox box5;
    private javax.swing.JCheckBox box6;
    private javax.swing.JCheckBox box7;
    private javax.swing.JCheckBox box8;
    private javax.swing.JCheckBox box9;
    private javax.swing.JFormattedTextField dateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lastText;
    private javax.swing.JTextField mailText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
